VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Plan88"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True

Private Sub cmdAnexos_Click()
    frmAnexosArquivos.Show
End Sub

Private Sub cmdCadastro_Click()
    frmCadastro.Show
End Sub

Private Sub cmdPesquisar_Click()
    frmPesquisar.Show
End Sub

Private Sub cmdProjeto_01_Click()
    
    ProjetoAtual = "C"
    frmPojeto.Show
    
End Sub

Private Sub cmdProjeto_02_Click()
    
    ProjetoAtual = "D"
    frmPojeto.Show
    
End Sub

Private Sub cmdProjeto_03_Click()
    
    ProjetoAtual = "E"
    frmPojeto.Show
    
End Sub

Private Sub cmdProjeto_04_Click()
    
    ProjetoAtual = "F"
    frmPojeto.Show
    
End Sub

Private Sub cmdProjeto_05_Click()
    
    ProjetoAtual = "G"
    frmPojeto.Show
    
End Sub

Private Sub cmdProjeto_06_Click()
    
    ProjetoAtual = "H"
    frmPojeto.Show
    
End Sub

Private Sub cmdProjeto_07_Click()
    
    ProjetoAtual = "I"
    frmPojeto.Show
    
End Sub

Private Sub cmdProjeto_08_Click()
    
    ProjetoAtual = "J"
    frmPojeto.Show
    
End Sub


